config/routes.rb
Rails.application.routes.draw do
  root to: 'folders#index'
  # Devise routes for API clients (custom sessions controller)
  require "sidekiq/web"
  # authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  # end

  devise_scope :user do
    post 'api/v1/login', to: 'users/sessions#create'
    delete 'api/v1/logout', to: 'users/sessions#destroy'
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get 'unsaved_tabs', to: 'tabs#unsaved_tabs'
  delete 'unsaved_tabs', to: 'tabs#destroy_unsaved_tabs'


  get 'fetch_folders', to: 'folders#fetch_folders'


  post 'users/login_from_ext', to: 'users#login_from_ext'
  resources :folders do
    resources :tabs, shallow: true
    post "saveall", to: 'tabs#save_all', as: 'save_all'
    resources :shares, shallow: true
  end
  get 'auth/request', to:'users#google_oauth2'
  resources :tabs, only: [:index]
  get 'pages/home', to: 'pages#home'

  get 'folders/:id/like', to: 'folders#like', as: 'like_folder'
end

app/models/folder.rb
require 'open-uri'

class Folder < ApplicationRecord
  belongs_to :user
  has_many :tabs, dependent: :destroy
  validates :name, presence: true, uniqueness: { scope: :user_id }
  # validates :name, uniqueness: { scope: :user_id }
  has_one_attached :photo

  # sharing
  has_many :shares, dependent: :destroy
  has_many :users, through: :shares

  after_create :run_photo_worker

  include PgSearch::Model
  pg_search_scope :search_folder,
  against: [:name],
  associated_against: {
    tabs: [:title, :url]
  },
  using: {
    # partial words allowed
    tsearch: { prefix: true }
  }

  def run_photo_worker
    AttachPhotoWorker.perform_async(id)
  end

  def attach_unsplash
    url = "https://source.unsplash.com/1600x900/?nature"
    unless self.photo.attached?
      puts "attaching unsplash photo.."
      self.photo.attach(io: open(url), filename: SecureRandom.hex(8))
    end
  end
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_action :set_folder, only: [:show, :edit, :update, :destroy, :like]

  def index

    @share = Share.all
    # if params[:query].present?
      # @folders = Folder.search_folder(params[:query])
    #   @folders = Folder.joins(:shares).where("folders.user_id = :id OR shares.user_id = :id", id: current_user.id)

    # else
    folders = policy_scope(Folder).joins("LEFT JOIN shares ON shares.folder_id = folders.id").where("folders.user_id = :id OR shares.user_id = :id", id: current_user.id).order(:id)
    @folders = folders.where.not(folders: {name: 'Default'}).reorder("folders.importance DESC, folders.updated_at DESC")
    # end
    @folder = Folder.new

    # returns a response to the get request
    # to confirm success. To display all folders
    # in chrome extension
    respond_to do |format|
      format.html
      format.json { render json: folders }
    end
  end

  def fetch_folders
    authorize :folder, :fetch_folders?
    render json: policy_scope(Folder).joins("LEFT JOIN shares ON shares.folder_id = folders.id").where("folders.user_id = :id OR shares.user_id = :id", id: current_user.id).order(:id).where.not(folders: {name: 'Default'})
  end

  def show
    @tab = Tab.new
    @share = Share.new
    @users = User.all
    authorize @folder
    # raise
  end

  # def new
  #   authorize @folder
  #   @folder = Folder.new
  # end

  def create
    @folder = Folder.new(folder_params)
    @folder.user_id = current_user.id
    authorize @folder


    if @folder.save
      # returns a response to the post request
      # to confirm success. To create new folder
      # from chrome extension
      respond_to do |format|
        format.html { redirect_to root_path }
        format.json { render json: { msg: 'success', folder: @folder } }
      end
    else
      puts @folder.errors.full_messages
      render :new
    end
  end

  def edit
    authorize @folder
  end

  def update
    authorize @folder
    if @folder.update(folder_params)
      redirect_to folder_path(@folder)
    else
      render :index
    end
  end

  def destroy
    authorize @folder
    @folder.destroy
    redirect_to root_path
  end

  def like
    authorize @folder

    puts "liking a folder..."

    if @folder.importance
      @folder.update importance: false
    else
      @folder.update importance: true
    end

    # importance = !@folder.importance

    # @folder.update importance: importance
    # redirect_to root_path
    # redirect_back(fallback_location: root_path)
    render json: {
      msg: 'Success'
    }
  end

  private

  def set_folder
    @folder = Folder.find(params[:id])
  end

  def folder_params
    params.require(:folder).permit(:name, :importance, :coverimg, :user_id, :photo)
  end
end

app/views/folders/_create_folder.html.erb
  <button class="btn-primary btn-lg" id="show-folder-form">Create a folder</button>
  <div id="new-folder-form" class="hidden">
    <div class="form">
      <button id="close-folder-form" class="btn-primary btn-sm">close</button>
      <h3>Create Folder</h3>
      <%= simple_form_for(@folder) do |f| %>
        <%= f.input :name, placeholder: 'Add a folder name' %>
        <%= f.input :photo, as: :file %>
        <%= f.submit "Add folder", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>

app/views/folders/edit.html.erb
<%= simple_form_for(@folder) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

app/views/folders/index.html.erb
<%= render 'layouts/navbar' %>
<% if @folders.count < 1 %>
  <div class="d-flex container-new justify-content-center align-items-center">
    <div class="">
      <h1 class="new-folder-heading">Get started by creating a new folder ⤴</h1>
      <div class="new-folder-gif">
      </div>
    </div>
  </div>
<% else %>
  <div class="cards">
    <% @folders.each do |folder| %>
      <div id="folder-card" data-id="<%= folder.id %>" class="card" style="background-image: linear-gradient(to bottom, rgba(255,255,255,0.12) 0, rgba(0,0,0,0.55) 74.4%),url(<%= folder.photo.attached? ? folder.photo.service_url : 'https://source.unsplash.com/1600x900/?nature/100X250'%>)" >
        <div class="goto-view">
            View
        </div>
        <div class="goto-name">
            <%= folder.name %>
        </div>
        <div class = "time">
            <%= folder.created_at.strftime("%m/%d/%Y")%>
        </div>
        <!-- <img class="fav-heart" src="/assets/images/heart.png" alt="okkkkk"> -->
        <%#= link_to like_folder_path(folder) do %>
          <div id="fav-heart" class="fav-heart" data-id="<%= folder.id %>">
            <% if folder.importance? %>
                <%= image_tag "heart.png", :class => 'heart-pic'%>
            <% else %>
                <%= image_tag "unlike.png", :class => 'heart-pic unlike-heart'%>
            <% end %>
          </div>
        <%# end %>
      </div>
    <% end %>
  </div>
<% end %>


<!--  create a new route that goes to folder controller to like or unlike a folder
  create the action in the controller to like or unlike a folder
  add link tag to
 -->

app/views/folders/show.html.erb
<%= render 'layouts/navbar_showpage' %>
<div class="show-header">
  <div class="show-title">
    <h1><%= @folder.name %></h1>
  </div>
</div>

  <div class="show-page-content">
    <div class="col-8">
      <div class="show-content">
        <div id="show-tabs-folder">
          <% @folder.tabs.each do |tab|  %>
              <div class="show-tab-card">
                  <div class="show-tab-content">
                      <div class="show-tab-title">
                          <% if tab.icon %>
                            <img src="<%= tab.icon %>" class="tab-icon">
                          <% else %>
                            <img src="https://res.cloudinary.com/xiway/image/upload/v1619698013/T_logo_g2dfsq.png" alt="default-icon" class="tab-icon">
                          <% end %>
                        <h3> <%= tab.title %> </h3>
                      </div>
                        <div class="show-tab-actions">
                          <div id="tab-edit" data-id="<%= tab.id %>">
                              <i class="fas fa-pen"></i>
                          </div>
                        <div class="tab-update">
                          <div id="tab_update_<%= tab.id %>" class="hidden">
                            <div class="tab-update-title">
                              <button id="close-edit-tab-show" data-id="<%= tab.id %>">
                                <i class="fas fa-times"></i>
                              </button>
                             <%= simple_form_for(tab) do |f| %>
                             <div class="edit-tab-title">
                              <%= f.input :title %>
                            </div>
                            <div class="save-edit">
                              <%= f.button :submit, 'Save' %>
                            </div>
                            <% end %>
                          </div>
                        </div>
                      </div>
                          <div class="tab-delete">
                            <%= link_to tab_path(tab), method: :delete, data: {confirm: "Are you sure to delete this tab?"} do %>
                              <i class="far fa-trash-alt"></i>
                            <% end  %>
                          </div>
                        </div>
                          <% link = tab.url %>
                        <%= link_to link, target: "_blank"  do %>
                      <div class="show-tab-url">
                        <%= tab.url.truncate(80, seperator: '', omission: '...') %>
                      </div>
                    </div>
              </div>
            <% end %>
          <% end %>
        </div>
    </div>
  </div>

    <div class="col-4">
      <div class="show-card" style="background-image: linear-gradient(to bottom, rgba(255,255,255,0.12) 0, rgba(0,0,0,0.55) 74.4%), url(<%= @folder.photo.attached? ? cl_image_path(@folder.photo.key) : "https://source.unsplash.com/1600x900/?nature" %>)">
        <div id="show-share-form" class="folder-btn">
              Share
        </div>
          <div id="new-share-form" class="hidden">
            <button id="close-share-form">
              <i class="fas fa-times"></i>
            </button>
              <h3>Who to share with?</h3>
                <%= simple_form_for([@folder, @share]) do |f| %>
                  <select name="share[user_id]" id="" data_behavior="choicesjs" class="share-select">
                    <%= @users.each do |user| %>
                     <option value="<%= user.id %>"><%= user.email %></option>
                  <% end %>
                  </select>
                <div class="share-btn">
                  <%= f.submit "Share" %>
                </div>
              <% end %>
          </div>
            <div id="edit-folder" class="folder-btn">
              Edit
            </div>

            <div id="show-edit-folder" class="hidden">
              <button id="close-edit-folder">
                   <i class="fas fa-times"></i>
              </button>
                <h3>Edit folder</h3>
                <div class="edit-form">
                  <%= simple_form_for(@folder) do |f| %>
                    <div class="edit-name">
                      <%= f.input :name %>
                    </div>
                    <div class="edit-cover">
                      <%= f.input :photo, as: :file %>
                    </div>
                    <div class="edit-btn">
                      <%= f.submit %>
                    </div>
                  <% end %>
                </div>
            </div>
          <%= link_to folder_path(@folder), method: :delete, data: {confirm: "Are you sure to delete the folder and all of its contents?"} do %>
            <div class="folder-btn">
              Delete
            </div>
          <% end %>
      </div>
    </div>